### PR TITLE
Improve text

### PR DESCRIPTION
**Pull request by RickAstly**
Improves text everywhere, most notably fixing readme and cleaning up a few quests.

### CODE REVIEW

**Comment by BalaM314** [comment]
...Why does it say "add rickrolls"

**Comment by RickAstly** [comment]
thats nothing

**Comment by BalaM314** [comment]
ok

**Comment by RickAstly** [comment]
Ƅԝɧᾱɧᾀḣȧ ẻὖềґӳṍŉẻṧ ցṏᾓńᾂ ɡḕʈ ɽıċǩгǒɭɫḙḓ ńỏẇ

**Comment by BalaM314** [comment]
what is that weird text I cant read that

**Pull request merged**
